### PR TITLE
Added OSINT source selection options

### PR DESCRIPTION
**Pull request by ryanborum**
Made some changes to allow users to choose which sources they'd like (if they don't want to use all defaults) - this required an options menu which should open the door for more flexibility if desired (new windows vs open in tabs, etc) - let me know what you think:

Added options menu
Added multiple-value selects to choose sources
Refactored main script a bit to reduce URL redundancy

### CODE REVIEW

**Comment by AdamMOdell** [comment]
I'm not sure if your code works. I tested this out and was able to open the options menu and save new settings, but when I used the extension on IOCs it still opened up the entire list of default OSINT URLs. If the problem is with your code, and not my testing methodology, I think the bug is in script.js function get_osint_urls_by_ioc_type. If this works on your browser can you share in detail your testing methodology?

**Comment by AdamMOdell** [comment]
image
Here's the options I saved when testing. On all 3 IOC types it opens the full URL list.

**Comment by ryanborum** [comment]
@AdamMOdell  I pushed a fix - you're right that the function wasn't working correctly. Chrome storage key names are now hard-coded in each IOC if/then case rather than using a function taking the key name as an argument and it seems to work locally for me.

**Comment by AdamMOdell** [comment]
I tested it and it works. Nice job! Merging, it'll go into the next version once I've added a couple more features.

**Pull request merged**
